project:
  type: website
  output-dir: "docs"
website:
  title: "Xách tay Đức Pháp Bỉ"
  navbar:
    left: 
      - text: Mỹ phẩm
        href: mypham.qmd
      - text: Nước hoa
        href: nuochoa.qmd
      - text: Túi xách
        href: tuixach.qmd
      - text: Thực phẩm chức năng
        href: tpcn.qmd
      - text: Trang sức
        href: trangsuc.qmd
      - text: Đồ em bé
        href: embe.qmd
    right:
      - icon: globe
        text: "Zalo"
        href: https://zalo.me/84364367938
google-analytics: G-YWJ031H8H6
format:
  html:
    theme:
      - cosmo
      - brand
      - styles.scss

editor: visual

