---
title: "Khóa học online của chúng tôi"
format: html
---

## Lớp Poto (trình độ A1-A2)

Khóa học này cung cấp cho bạn:

- 1 buổi meeting live học thử

- Những kiến thức ngữ pháp, từ vựng cơ bản

- Những chủ đề giao tiếp hằng ngày

- Những bộ đề luyện thi được biên soạn công phu

- 1 buổi luyện giao tiếp trực tiếp với người Pháp/Bỉ (có thể có)

## Lớp Tintin (trình độ B1)

Khóa học này cung cấp cho bạn::

- 1 buổi meeting live học thử

- Những kiến thức ngữ pháp, từ vựng nâng cao

- Những chủ đề giao tiếp nâng cao

- Những bộ đề luyện thi được biên soạn công phu

- 1 buổi luyện giao tiếp trực tiếp với người Pháp/Bỉ (có thể có)

## Lớp Schtroumpf (trình độ B2)

Khóa học này cung cấp cho bạn:

- 1 buổi meeting live học thử

- 2 buổi luyện giao tiếp trực tiếp với người Pháp/ Bỉ

- Hoàn thiện khả năng sử dụng ngôn ngữ, tranh luận, viết luận, thuyết trình bằng tiếng Pháp

## Lớp Coucou (trình độ C1)

Khóa học này cung cấp cho bạn:

- 1 buổi meeting live học thử

- 2 buổi luyện giao tiếp trực tiếp với người Pháp/ Bỉ

- Hoàn thiện khả năng sử dụng ngôn ngữ, tranh luận, viết luận, thuyết trình bằng tiếng Pháp nâng cao

📝 **Bạn quan tâm?** Hãy liên hệ với chúng tôi qua **WhatsApp, Instagram, Facebook hoặc Email**